<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Himendra.Portfolio.Application\Himendra.Portfolio.Application.csproj" />
    <ProjectReference Include="..\Himendra.Portfolio.Domain\Himendra.Portfolio.Domain.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
